---

version: "3.8"

services:
  cash_test_postgres:
    container_name: CashService_TestPostgres
    image: postgres:13.3
    pull_policy: if_not_present
    environment:
      - POSTGRES_DB=CashDbIntegrationTest
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
    healthcheck:
      test:
        [
          "CMD-SHELL",
          "pg_isready -U postgres -d CashDbIntegrationTest"
        ]
      interval: 10s
      timeout: 5s
      retries: 10
      start_period: 10s
    volumes:
      - postgres_volume:/var/lib/postgresql/data
    logging:
      driver: none

  cash_test_migrator:
    container_name: CashService_TestMigrator
    image: mcr.microsoft.com/dotnet/sdk:6.0
    pull_policy: if_not_present
    environment:
      - ASPNETCORE_ENVIRONMENT=IntegrationTest
      - DbConn=Host=cash_test_postgres;Port=5432;Database=CashDbIntegrationTest;User Id=postgres;Password=postgres
    volumes:
      - ./../../src:/app-migrator/src
      - ./../../devops:/app-migrator/devops
    command:
      [
        "dotnet",
        "run",
        "--project",
       "/app-migrator/src/CashService.DatabaseMigrator/CashService.DatabaseMigrator.csproj",
        "--connection-string-source",
        "env",
        "--connection-string-env-variable-name",
        "DbConn"
      ]
    depends_on:
      cash_test_postgres:
        condition: service_healthy

  integration_tests:
    container_name: CashService_IntegrationTests
    build:
      context: ./../../
      dockerfile: ./tests/CashService.IntegrationTests/Dockerfile
    environment:
      - ASPNETCORE_ENVIRONMENT=IntegrationTest
      - CashService_ConnectionStrings__CashDb=Host=cash_test_postgres;Port=5432;Database=CashDbIntegrationTest;User Id=postgres;Password=postgres
    depends_on:
      cash_test_migrator:
        condition: service_completed_successfully

  functional_tests:
    container_name: CashService_FunctionalTests
    build:
      context: ./../../
      dockerfile: ./tests/CashService.FunctionalTests/Dockerfile
    environment:
      - ASPNETCORE_ENVIRONMENT=IntegrationTest
      - CashService_ConnectionStrings__CashDb=Host=cash_test_postgres;Port=5432;Database=CashDbIntegrationTest;User Id=postgres;Password=postgres
    depends_on:
      cash_test_migrator:
        condition: service_completed_successfully

volumes:
  postgres_volume:
    driver_opts:
      type: tmpfs
      device: tmpfs
